from typing import List, Dict, Tuple
from src.Zone import Zone
from src.Connection import Connection
from src.Parser import Parser


class Network:
    """
    Topology manager. Take a raw list of dictionaries generated by Parser
    and convert them into actual Zone and Connection objects.
    """
    def __init__(self, parser: Parser) -> None:
        """
        Initialize the Network by converting parser data into objects.
        """
        self.parser = parser
        self.zones: Dict[str, Zone] = {}
        self.connections: List[Connection] = []
        self.neighboring_zones: Dict[str, List[Tuple[Zone, Connection]]] = {}
        self._assign_zones_and_connections()
        self._assign_neighboring_zones()

    def _assign_zones_and_connections(self) -> None:
        """
        Instantiate Zone and Connection objects from the parsed dictionary
        data.
        """
        if self.parser.start_hub is not None:
            zone = Zone(**self.parser.start_hub)
            self.zones[zone.name] = zone

        for hub_data in self.parser.hubs:
            zone = Zone(**hub_data)
            self.zones[zone.name] = zone

        if self.parser.end_hub is not None:
            zone = Zone(**self.parser.end_hub)
            self.zones[zone.name] = zone

        for con_data in self.parser.connections:
            connection = Connection(**con_data)
            self.connections.append(connection)

    def _assign_neighboring_zones(self) -> None:
        """
        Build an adjacency list mapping each zone to its
        connected neighbors and their corresponding connection.
        """
        for zone_name in self.zones:
            self.neighboring_zones[zone_name] = []

        for con in self.connections:
            zone1 = self.zones[con.name1]
            zone2 = self.zones[con.name2]
            self.neighboring_zones[con.name1].append((zone2, con))
            self.neighboring_zones[con.name2].append((zone1, con))
