from typing import List, Dict, Tuple
from src.Zone import Zone
from src.Connection import Connection
from src.Parser import Parser


class Network:
    """
    Topology manager. Take a raw list of dictionaries generated by Parser
    and convert them into actual Zone and Connection objects.
    """
    def __init__(self, parser: Parser):
        self.parser = parser
        self.zones: Dict[str, Zone] = {}
        self.connections: List[Connection] = []
        self.neighboring_zones: Dict[str, List[Tuple[Zone, Connection]]] = {}
        self._assign_zones_and_connections()
        self._assign_neighboring_zones()

    def _assign_zones_and_connections(self) -> None:
        if self.parser.start_hub is not None:
            zone = Zone(**self.parser.start_hub)
            self.zones[zone.name] = zone

        for hub_data in self.parser.hubs:
            zone = Zone(**hub_data)
            self.zones[zone.name] = zone

        if self.parser.end_hub is not None:
            zone = Zone(**self.parser.end_hub)
            self.zones[zone.name] = zone

        for con_data in self.parser.connections:
            connection = Connection(**con_data)
            self.connections.append(connection)

    def _assign_neighboring_zones(self) -> None:
        for zone_name in self.zones:
            self.neighboring_zones[zone_name] = []

        for con in self.connections:
            zone1 = self.zones[con.name1]
            zone2 = self.zones[con.name2]
            self.neighboring_zones[con.name1].append((zone2, con))
            self.neighboring_zones[con.name2].append((zone1, con))

    def canvas_size(self) -> Tuple[int, int]:
        if not self.zones:
            self.size = (0, 0)
            return self.size

        x_coords = [zone.x for zone in self.zones.values()]
        y_coords = [zone.y for zone in self.zones.values()]

        self.canvas_min_x = min(x_coords)
        self.canvas_max_x = max(x_coords)
        self.canvas_min_y = min(y_coords)
        self.canvas_max_y = max(y_coords)

        width = self.canvas_max_x - self.canvas_min_x + 1
        height = self.canvas_max_y - self.canvas_min_y + 1
        self.size = (width, height)
        return self.size
